name: Phylum Analyze
on:
    pull_request:
    # pull_request_target:
    #     types: [labeled, opened, synchronize, reopened]
    #     paths:
    #         - "ingestion/**"
    #         - "openmetadata-service/**"
    #         - "openmetadata-ui/**"

jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    environment: test
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

      - name: Wait for the labeler
        uses: lewagon/wait-on-check-action@v1.3.3
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: Team Label
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 90
      - name: Verify PR labels
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'safe to test'
          pull-request-number: '${{ github.event.pull_request.number }}'
          disable-reviews: true  # To not auto approve changes
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Python Dependencies
        run: |
          python3 -m venv env &&
          source env/bin/activate &&
          pip install phylum=~0.47.0
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Analyze dependencies
        env:
          PHYLUM_API_KEY: ${{ secrets.PHYLUM_TOKEN }}
        run: |
          phylum auth login && \
          phylum analyze -vv --skip-sandbox -p OpenMetadata